### PR TITLE
Force reload config after plugin is loaded

### PR DESCRIPTION
**Pull request by sant0s12**
See https://github.com/hyprwm/Hyprland/issues/4144 and https://github.com/hyprwm/hyprland-plugins/blob/145d8c6fa6fb41d959a2f6e6b94cfe93aa7e77b6/borders-plus-plus/main.cpp#L44.

### CODE REVIEW

**Comment by outfoxxed** [comment]
Sorry, I'd missed this. @sant0s12 is this still a concern post-hyprlang?

**Comment by sant0s12** [comment]
I think so. The problem is that things like `hy3:movefocus` are only defined once hy3 is loaded, therefore hyperland shows an error when the config is first loaded (even with `exec-once = hyprpm reload -n`).

Reloading the config after hy3 is loaded fixes that.

**Comment by dcaixinha** [comment]
Jumping to say that I'm facing the same issue loading `hy3` with just the barebones config from the README (and a `exec-once = hyprpm reload -n` on `hyprland.conf`).

After I edit the config with some value, just to trigger a config reload, the error goes away and everything works!

**Comment by outfoxxed** [comment]
Rebased and merged

**Pull request closed without merging**
