### PR TITLE
Fix tab bar visual defects when switching workspaces

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/outfoxxed/hy3/issues/100

---

~~The current solution is very hack and needs to be improved~~

### CODE REVIEW

**Comment by outfoxxed** [comment]
I'm not seeing any improvement with this

https://github.com/outfoxxed/hy3/assets/83010835/81bc811d-e878-41cd-9a82-bc5a9242a451


https://github.com/outfoxxed/hy3/assets/83010835/598097a7-f8ea-42db-9615-d49ecda98a60

**Comment by SimonBrandner** [comment]
The reason it doesn't work for you is scaling, however weird that sounds - no idea why yet...

**Comment by SimonBrandner** [comment]
@outfoxxed, I have updated the PR with the best solution I can currently think of - let me know if it is acceptable...

**Comment by SimonBrandner** [comment]
@outfoxxed, I think the current version should hopefully cover all the issues. The fix is quite simple, not exactly happy it took me so much time to get it done... :sweat_smile:

**Comment by outfoxxed** [comment]
Looks good to me but it appears master is behaving weirdly. Going to give upstream a day or a few and see if that fixes itself, if not fix whatever's segfaulting there, then merge this.

**Comment by SimonBrandner** [comment]
I am not seeing any segfaults myself though I haven't updated upstream in a while, let me know if you have any updates

**Comment by outfoxxed** [comment]
Missed something in my last fix against upstream and didn't test it. That's dealt with now and it seems to work.

**Comment by SimonBrandner** [comment]
Awesome - thanks!

**Pull request merged**
