### PR TITLE
Fix the behaviour for multi-monitor setups

### LINKED ISSUE #2: `hy3:movefocus` doesn't change monitor
When using multiple monitors, moving the focus or a window towards the other monitor doesn't change the monitor/workspace.

### Expected behavior:
Using `hy3:movefocus` or `hy3:movewindow` against the edge of the monitor moves to the workspace on the next monitor like `movefocus` and i3/sway.

### Actual behavior:
`hy3:movefocus` stops at the edge of the monitor.

### PR DESCRIPTION
**Pull request by ChrisRuff**
Mainly a revival for #5, but created in the shiftOrGetFocus. This also selects the previously selected window on the workspace (which mimics i3 more correctly).

Closes #2

### CODE REVIEW

**Comment by ChrisRuff** [comment]
With this implementation there are two bugs I'm struggling to solve:
1. When a window is fullscreen, or you switch to an empty workspace, moving focus doesnt work. 
2. When moving a window to a monitor to the right, the window should be on the left of the workspace, but instead it appears on the right. 

Any tips or guidance on how I could fix that would be greatly appreciated

**Comment by outfoxxed** [comment]
1. when on an empty workspace, no node is selected and there is no point of reference to move from.
2. the node is appended after the last focused node in the given workspace

**Comment by ChrisRuff** [comment]
So fixed the issues with fullscreen/empty workspaces, but im still completely skipping the complex logic you have in shiftOrGetFocus when it comes to shifting the nodes to the adjacent monitor, mainly because im not sure where moving the node to the adjacent monitor would fit in there. Do you have any ideas @outfoxxed? I still need to fix the location of where shifted windows appear.

**Comment by outfoxxed** [comment]
I think if `once` then wrap the root node on the new monitor and insert the moved node next to the old root. if not then insert it into that group.

**Comment by outfoxxed** [comment]
I tested this and it seemed to work correctly, so I've merged it.

**Pull request merged**
